### PR TITLE
feat(Dockerfile): add Dockerfile for service broker

### PR DESCRIPTION
**Pull request by arschles**

### CODE REVIEW

**Comment by thausler786** [comment]
Can you give us a bit more context on this addition? That will help us determine whether we merge it in or not.

Thanks,

@thausler786 & @rizwanreza
The CAPI Team Members

**Comment by arschles** [comment]
@thausler786 sure! Adding this `Dockerfile` allows one to run the following from the top level of this repository:

```console
docker build -t my/docker/image service_broker
```

The end result will be a docker image called `my/docker/image` that will run the service broker if you run the following command:

```console
docker run --rm my/docker/image
```

The image can also be published to a docker repository such as [Docker Hub](https://hub.docker.com/) or [Quay.io](https://quay.io/).

In total, this ability to create and publish docker images holding the broker is helpful for running this service broker in cluster management systems like [Kubernetes](http://kubernetes.io/) (which I'm currently using it for), [Docker Swarm](https://docs.docker.com/swarm/), [Apache Mesos](http://mesos.apache.org/) and, of course, [CloudFoundry's integration with Docker](https://docs.pivotal.io/pivotalcf/1-7/concepts/docker.html) (which I presume you're familiar with).

**Comment by thausler786** [comment]
@arschles looks good, we'll merge it!

@thausler786 && @rizwanreza, CAPI team members

**Comment by arschles** [comment]
Thanks @thausler786

**Pull request merged**
